### ISSUE TITLE
requireAdministrator

### ISSUE THREAD

**Issue by nickbouwhuis** [Dysanix/SessionSweeper#1]
Your application needs to manually be run as administrator. I recommend adding the "requireAdministrator" option to your manifest :)

Also, check: https://msdn.microsoft.com/en-us/library/windows/desktop/dd550643(v=vs.85).aspx

**Comment by Dysanix** [comment]
I have thought about it.. However, since some features of the application don't need Administrator rights I figured I wouldn't make it a necessity. This allows people without administrator rights to still enjoy the other features (mostly kids with parental control).

**Comment by nickbouwhuis** [comment]
Ah, check. Thanks for your response!
